# GitHub action to verify `clarinet check` runs against contract
# Uses a prepare script outlined in testing section of README

name: CI Clarinet

# Controls when the action will run.
on:
  push:

concurrency:
  group: 'ci-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    name: check - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true      
      - name: "Check contract"
        uses: docker://hirosystems/clarinet:0.27.0
        with:
          entrypoint: "bash"
          args: -c "clarinet check"
  test:
    name: test - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true      
      - name: "Set CI env"
        run: |
          echo "ci_env=$(bash <(curl -s https://codecov.io/env))" >> $GITHUB_ENV
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:0.27.0
        with:  
          entrypoint: "bash"
          #args: -c "clarinet test --coverage && curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage.lcov"
          args: -c "clarinet test --coverage"
